title: Vinay Kotwani
#logo: /assets/img/headshot.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-slate
defaults:
  - scope:
      path: ""
    values:
      sitemap: false
